name: kasir
description: A cashier application with POS, product management, and AI recommendations.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  mobile_scanner: ^3.5.6
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  csv: ^5.1.1
  share_plus: ^7.2.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true